In [63]:
import pandas as pd
!pip install openpyxl
import openpyxl

Requirement already satisfied: openpyxl in /Users/akeem/anaconda3/envs/tf_mar_2025/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/akeem/anaconda3/envs/tf_mar_2025/lib/python3.12/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.0.1 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [64]:
df = openpyxl.load_workbook('/Users/akeem/Downloads/Book2.xlsm')
sheets = df.sheetnames
ws = df[sheets[0]]

found = {}

# Remove column 2
ws.delete_cols(2)
saved_name = -1
#loop through rows, grab value in col 1. Check if it is a url
for row in ws.iter_rows(min_row=2, max_col=1):
    for cell in row:
        value = cell.value
        if isinstance(value, str) and value.startswith('http'):
            print(f"Found name: {saved_name} with url: {value}")
            found[saved_name] = value
            saved_name = -1
        elif isinstance(value, str) and ", " in value and "Also" not in value and "Story-" not in value:
            saved_name = value
            found[saved_name] = None
            #print(f"Found name: {saved_name}")

found

Found name: -1 with url: https://public.tableau.com/app/profile/sejal.sejal8318/viz/Story_17644863492760/Story1?publish=yes
Found name: -1 with url: https://public.tableau.com/app/profile/sejal.sejal8318/viz/Story_17644863492760/Story1?publish=yes
Found name: Friesen, Adelle with url: https://public.tableau.com/app/profile/adelle.friesen/viz/Storyforassignment_17643791578200/Story1?publish=yes
Found name: Frost, Martina with url: https://public.tableau.com/shared/HHJHGCFTN?:display_count=n&:origin=viz_share_link
Found name: Garcia Moreira Santos, Breno with url: https://public.tableau.com/views/Assignment3-Story-BrenoSantos/Story?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Gurtar Singh, . with url: https://public.tableau.com/views/StoryDATA2210/Story1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Hounsell, Tori with url: https://public.tableau.com/views/ProvinceGDPStory/GDPOveraDecade?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Janat Madaan, . with url: https://public.tableau.com/app/profile/janat.madaan/viz/storyassignment_17644848839990/CrimeLevelsinEdmontonHaveShiftedSignificantlyfrom20092018?publish=yes
Found name: Jia, Skylar with url: https://public.tableau.com/views/Book12_17644762353710/Sheet2?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Kaur, Jaipreet with url: https://public.tableau.com/app/profile/user125/viz/Netfilx_top_10_Story/NetflixTop10InsightsOverview?publish=yes
Found name: Khushi, . with url: https://public.tableau.com/app/profile/user125/viz/TheImpactofCO2EmissionsonGlobalTemperatureChangestorytelling/TheImpactofCO2EmissionsonGlobalTemperatureChange?publish=yes
Found name: Khushpreet Singh, . with url: https://public.tableau.com/app/profile/khushpreet.singh5138/viz/storyassignment_17644012160210/EdmontonCrimeAnalysisStory20092018?publish=yes
Found name: Knoppers, Jacob with url: https://public.tableau.com/app/profile/jacob.knoppers/viz/JacobKnoppers_StoryAssignment/Story1?publish=yes
Found name: Kohli, Brahmmeet Singh with url: https://public.tableau.com/views/BankCustomerChurnStory_17644838405010/CustomerChurnStory?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Lavallee, Danielle with url: https://public.tableau.com/shared/KJPB8T6GC?:display_count=n&:origin=viz_share_link
Found name: Liboiron, Liam with url: https://public.tableau.com/app/profile/liam.liboiron/viz/StoryLiam/Story?publish=yes
Found name: Libuna, Chira May with url: https://public.tableau.com/shared/KRYWZ2P82?:display_count=n&:origin=viz_share_link
Found name: Lnu, Simranpreet Kaur with url: https://public.tableau.com/app/profile/simranpreet.kaur.lnu/viz/WardCompositioninEdmonton/WardResidentDemographics?publish=yes
Found name: Martineau, Kenzie with url: https://public.tableau.com/views/HowWeatherAffectsTransitRidershipinEdmonton/HowWeatherAffectsTransitRidershipinEdmonton?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Na, Tanishka with url: https://public.tableau.com/shared/PJPQPTX2P?:display_count=n&:origin=viz_share_link
Found name: Ogbodu, Kennedy with url: https://public.tableau.com/app/profile/kennedy.ogbodu/viz/HowCrimeDiffersAcrossEdmontonNeighbourhoodstheMostImpactfulCrimeTrendsOverTime/Story1#1
Found name: Pardeep Kaur, . with url: https://public.tableau.com/views/StoryAssignment_17644451832430/Dashboard1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Peng, Aesir with url: https://public.tableau.com/app/profile/aesir.peng/viz/StoryAssignment_17643996389390/TopCategories?publish=yes
Found name: Rohit, . with url: https://public.tableau.com/views/StoryRohit/Story1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Sewers, Pamela with url: https://public.tableau.com/app/profile/pamela.sewers/viz/Storyforassignment_17644343282830/Story1?publish=yes
Found name: Shang, Sarah with url: https://public.tableau.com/app/profile/sarah.shang2142/viz/SarahShangstory/Story1?publish=yes
Found name: Singh, Harmanjot with url: https://public.tableau.com/views/Storyyyy_17644855815170/Story1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Singh, Navraj with url: https://public.tableau.com/views/Story_17644630315480/Trendchart?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link
Found name: Singh, Sehajpal with url: https://public.tableau.com/app/profile/sehajpal.singh6709/viz/UDISEInfrastructureStory/Story1?publish=yes
Found name: Tervonen-Dueck, Addyson with url: https://public.tableau.com/app/profile/addyson.tervonen.dueck/viz/StoryAssignment_17644572536910/GreenhouseGasesPerIndustrySector?publish=yes
Found name: Tisha, . with url: https://public.tableau.com/app/profile/tisha.tisha4837/viz/TransitRidershipOn-TimePerformanceAnalysis/StoryPoint2
Found name: Van't Hoff, Edson with url: https://public.tableau.com/app/profile/edson.van.t.hoff/viz/StoryAssignment_17644378459260/Story1?publish=yes
Found name: Wagner-Joseph, Tyler with url: https://public.tableau.com/app/profile/tyler.wagner.joseph/viz/ChildsPlayfranchiseStorySaved/ChildsPlayFranchiseStory

{-1: 'https://public.tableau.com/app/profile/sejal.sejal8318/viz/Story_17644863492760/Story1?publish=yes',
 'Aginas, Gayle': None,
 'Apito, Abbygail': None,
 'Felipe, Katrina': None,
 'Friesen, Adelle': 'https://public.tableau.com/app/profile/adelle.friesen/viz/Storyforassignment_17643791578200/Story1?publish=yes',
 'Frost, Martina': 'https://public.tableau.com/shared/HHJHGCFTN?:display_count=n&:origin=viz_share_link',
 'Garcia Moreira Santos, Breno': 'https://public.tableau.com/views/Assignment3-Story-BrenoSantos/Story?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Gomms, Eagan': None,
 'Gurtar Singh, .': 'https://public.tableau.com/views/StoryDATA2210/Story1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Hounsell, Tori': 'https://public.tableau.com/views/ProvinceGDPStory/GDPOveraDecade?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Janat Madaan, .': 'https://public.tableau.com/app/profile/janat.madaan/viz/storyassignment_17644848839990/CrimeLevelsinEdmontonHaveShiftedSignificantlyfrom20092018?publish=yes',
 'Jia, Skylar': 'https://public.tableau.com/views/Book12_17644762353710/Sheet2?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Kajoba, Benjamin': None,
 'Kaur, Jaipreet': 'https://public.tableau.com/app/profile/user125/viz/Netfilx_top_10_Story/NetflixTop10InsightsOverview?publish=yes',
 'Khushi, .': 'https://public.tableau.com/app/profile/user125/viz/TheImpactofCO2EmissionsonGlobalTemperatureChangestorytelling/TheImpactofCO2EmissionsonGlobalTemperatureChange?publish=yes',
 'Khushpreet Singh, .': 'https://public.tableau.com/app/profile/khushpreet.singh5138/viz/storyassignment_17644012160210/EdmontonCrimeAnalysisStory20092018?publish=yes',
 'Knoppers, Jacob': 'https://public.tableau.com/app/profile/jacob.knoppers/viz/JacobKnoppers_StoryAssignment/Story1?publish=yes',
 'Kohli, Brahmmeet Singh': 'https://public.tableau.com/views/BankCustomerChurnStory_17644838405010/CustomerChurnStory?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Lavallee, Danielle': 'https://public.tableau.com/shared/KJPB8T6GC?:display_count=n&:origin=viz_share_link',
 'Liboiron, Liam': 'https://public.tableau.com/app/profile/liam.liboiron/viz/StoryLiam/Story?publish=yes',
 'Libuna, Chira May': 'https://public.tableau.com/shared/KRYWZ2P82?:display_count=n&:origin=viz_share_link',
 'Lnu, Simranpreet Kaur': 'https://public.tableau.com/app/profile/simranpreet.kaur.lnu/viz/WardCompositioninEdmonton/WardResidentDemographics?publish=yes',
 'Lovedeep, .': None,
 'Martineau, Kenzie': 'https://public.tableau.com/views/HowWeatherAffectsTransitRidershipinEdmonton/HowWeatherAffectsTransitRidershipinEdmonton?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Mclean, Aidan': None,
 'Mohamed, Doha': None,
 'Na, Tanishka': 'https://public.tableau.com/shared/PJPQPTX2P?:display_count=n&:origin=viz_share_link',
 'Ogbodu, Kennedy': 'https://public.tableau.com/app/profile/kennedy.ogbodu/viz/HowCrimeDiffersAcrossEdmontonNeighbourhoodstheMostImpactfulCrimeTrendsOverTime/Story1#1',
 'Pardeep Kaur, .': 'https://public.tableau.com/views/StoryAssignment_17644451832430/Dashboard1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Peng, Aesir': 'https://public.tableau.com/app/profile/aesir.peng/viz/StoryAssignment_17643996389390/TopCategories?publish=yes',
 'Rohit, .': 'https://public.tableau.com/views/StoryRohit/Story1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Sewers, Pamela': 'https://public.tableau.com/app/profile/pamela.sewers/viz/Storyforassignment_17644343282830/Story1?publish=yes',
 'Shang, Sarah': 'https://public.tableau.com/app/profile/sarah.shang2142/viz/SarahShangstory/Story1?publish=yes',
 'Singh, Harmanjot': 'https://public.tableau.com/views/Storyyyy_17644855815170/Story1?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Singh, Navraj': 'https://public.tableau.com/views/Story_17644630315480/Trendchart?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link',
 'Singh, Sehajpal': 'https://public.tableau.com/app/profile/sehajpal.singh6709/viz/UDISEInfrastructureStory/Story1?publish=yes',
 'Tervonen-Dueck, Addyson': 'https://public.tableau.com/app/profile/addyson.tervonen.dueck/viz/StoryAssignment_17644572536910/GreenhouseGasesPerIndustrySector?publish=yes',
 'Tisha, .': 'https://public.tableau.com/app/profile/tisha.tisha4837/viz/TransitRidershipOn-TimePerformanceAnalysis/StoryPoint2',
 "Van't Hoff, Edson": 'https://public.tableau.com/app/profile/edson.van.t.hoff/viz/StoryAssignment_17644378459260/Story1?publish=yes',
 'Wagner-Joseph, Tyler': 'https://public.tableau.com/app/profile/tyler.wagner.joseph/viz/ChildsPlayfranchiseStorySaved/ChildsPlayFranchiseStory',
 'Weir, Ethan': None}

In [65]:
found_df = pd.DataFrame.from_dict(found, orient='index', columns=['URL'])
found_df.reset_index(inplace=True)
found_df = found_df.rename(columns={'index': 'Name'})
found_df.to_csv('found_names_urls.csv', index=False)

In [66]:
process_subs = pd.DataFrame(columns=["Name", "URL"])
raw_links = []
raw_names = []
last_name = ""
last_url = ""
for i in range(len(submissions)):
    name = ""
    url = ""
    col_A_val = submissions.cell(i, 0).hyperlink.target if submissions.cell(i, 0).hyperlink else submissions.cell(i, 0).value
    if isinstance(col_A_val, str) and "http" in col_A_val:
        raw_links.append(col_A_val)
        last_url = col_A_val
    #elif isinstance(col_A_val, str) and not ("Comment" in col_A_val or "None" in col_A_val or "Story-" in col_A_val or "story" in col_A_val):
    elif ", " in str(col_A_val) and len(col_A_val) < 50 and not "Story-" in col_A_val:
        raw_names.append(col_A_val)
        last_name = col_A_val
    if len(last_name) > 0 and len(last_url) > 0:
        process_subs = pd.concat([process_subs, pd.DataFrame({"Name": [last_name], "URL": [last_url]})], ignore_index=True)
        last_name = ""
        last_url = ""

process_subs.tail(30)

AttributeError: 'DataFrame' object has no attribute 'cell'

In [ ]:
name_url_df = pd.read_csv("/Users/akeem/Downloads/found_names_urls.csv")
name_url_df["Count_Assigned"] = 0
#Add a column "Forum Title" to name_url_df
# and add a sequental value of VIS_001, VIS_002, etc. to the column
name_url_df["Forum Title"] = ["VIS_{:03d}".format(i) for i in range(1, len(name_url_df) + 1)]

name_url_df

,Name,URL,Count_Assigned,Forum Title
0,Sejal,https://public.tableau.com/app/profile/sejal.s...,0,VIS_001
1,"Aginas, Gayle",https://public.tableau.com/views/GayleAginas-D...,0,VIS_002
2,"Apito, Abbygail",https://public.tableau.com/shared/7CKX4B72J?:d...,0,VIS_003
3,"Felipe, Katrina",https://public.tableau.com/app/profile/katrina...,0,VIS_004
4,"Friesen, Adelle",https://public.tableau.com/app/profile/adelle....,0,VIS_005
5,"Frost, Martina",https://public.tableau.com/shared/HHJHGCFTN?:d...,0,VIS_006
6,"Garcia Moreira Santos, Breno",https://public.tableau.com/views/Assignment3-S...,0,VIS_007
7,"Gomms, Eagan",https://public.tableau.com/app/profile/eagan.g...,0,VIS_008
8,"Gurtar Singh, .",https://public.tableau.com/views/StoryDATA2210...,0,VIS_009
9,"Hounsell, Tori",https://public.tableau.com/views/ProvinceGDPSt...,0,VIS_010
10,"Janat Madaan, .",https://public.tableau.com/app/profile/janat.m...,0,VIS_011
11,"Jia, Skylar",https://public.tableau.com/views/Book12_176447...,0,VIS_012
12,"Kajoba, Benjamin",https://public.tableau.com/app/profile/benjami...,0,VIS_013
13,"Kaur, Jaipreet",https://public.tableau.com/app/profile/user125...,0,VIS_014
14,"Khushi, .",https://public.tableau.com/app/profile/user125...,0,VIS_015
15,"Khushpreet Singh, .",https://public.tableau.com/app/profile/khushpr...,0,VIS_016
16,"Knoppers, Jacob",https://public.tableau.com/app/profile/jacob.k...,0,VIS_017
17,"Kohli, Brahmmeet Singh",https://public.tableau.com/views/BankCustomerC...,0,VIS_018
18,"Lavallee, Danielle",https://public.tableau.com/shared/KJPB8T6GC?:d...,0,VIS_019
19,"Liboiron, Liam",https://public.tableau.com/app/profile/liam.li...,0,VIS_020
20,"Libuna, Chira May",https://public.tableau.com/shared/KRYWZ2P82?:d...,0,VIS_021
21,"Lnu, Simranpreet Kaur",https://public.tableau.com/app/profile/simranp...,0,VIS_022
22,"Lovedeep, .",https://public.tableau.com/app/profile/.lovede...,0,VIS_023
23,"Martineau, Kenzie",https://public.tableau.com/views/HowWeatherAff...,0,VIS_024
24,"Mclean, Aidan",https://public.tableau.com/app/profile/aidan.m...,0,VIS_025
25,"Mohamed, Doha",https://public.tableau.com/app/profile/doha.mo...,0,VIS_026
26,"Na, Tanishka",https://public.tableau.com/shared/PJPQPTX2P?:d...,0,VIS_027
27,"Ogbodu, Kennedy",https://public.tableau.com/app/profile/kennedy...,0,VIS_028
28,"Pardeep Kaur, .",https://public.tableau.com/views/StoryAssignme...,0,VIS_029
29,"Peng, Aesir",https://public.tableau.com/app/profile/aesir.p...,0,VIS_030
30,"Rohit, .",https://public.tableau.com/views/StoryRohit/St...,0,VIS_031
31,"Sewers, Pamela",https://public.tableau.com/app/profile/pamela....,0,VIS_032
32,"Shang, Sarah",https://public.tableau.com/app/profile/sarah.s...,0,VIS_033
33,"Singh, Harmanjot",https://public.tableau.com/views/Storyyyy_1764...,0,VIS_034
34,"Singh, Navraj",https://public.tableau.com/views/Story_1764463...,0,VIS_035
35,"Singh, Sehajpal",https://public.tableau.com/app/profile/sehajpa...,0,VIS_036
36,"Tervonen-Dueck, Addyson",https://public.tableau.com/app/profile/addyson...,0,VIS_037
37,"Tisha, .",https://public.tableau.com/app/profile/tisha.t...,0,VIS_038
38,"Van't Hoff, Edson",https://public.tableau.com/app/profile/edson.v...,0,VIS_039
39,"Wagner-Joseph, Tyler",https://public.tableau.com/app/profile/tyler.w...,0,VIS_040
40,"Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,0,VIS_041

In [97]:
# For each reviewer name in the name column, randomly select 4 URLs from the URL column that are not associated with that name
# create a new dataframe with columns: Reviewer Name, Submission Name, URL and insert the data accordingly
# Add a column to the name_url_df called "count" that shows how many times each URL has been assigned
import random
final_df = pd.DataFrame(columns=["Reviewer Name", "Submitter Name", "URL", "Forum for URL"])
all_reviewers = name_url_df["Name"].tolist()
random.shuffle(all_reviewers)
reviews_per_reviewer = 4
reviewer_count_dict = {name: 0 for name in all_reviewers}
position = 0
for index, row in name_url_df.iterrows():
    if position + reviews_per_reviewer < len(all_reviewers):
        reviewers = all_reviewers[position:position + reviews_per_reviewer]
    else:
        from_end = len(all_reviewers) - position
        from_start = reviews_per_reviewer - from_end
        reviewers = all_reviewers[position:] + all_reviewers[:from_start]
    position = (position + reviews_per_reviewer) % len(all_reviewers)
    for reviewer in reviewers:
        final_df = pd.concat([final_df, pd.DataFrame({"Reviewer Name": [reviewer], "Submitter Name": [row["Name"]], "URL": [row["URL"]], "Forum for URL": [row["Forum Title"]]} )], ignore_index=True)
        name_url_df.loc[name_url_df["Name"] == row["Name"], "Count_Assigned"] += 1
        reviewer_count_dict[reviewer] += 1

    final_df.to_csv("/Users/akeem/Downloads/2210_asn.csv", index=False)
final_df

,Reviewer Name,Submitter Name,URL,Forum for URL
0,"Pardeep Kaur, .",Sejal,https://public.tableau.com/app/profile/sejal.s...,VIS_001
1,"Apito, Abbygail",Sejal,https://public.tableau.com/app/profile/sejal.s...,VIS_001
2,"Gurtar Singh, .",Sejal,https://public.tableau.com/app/profile/sejal.s...,VIS_001
3,"Jia, Skylar",Sejal,https://public.tableau.com/app/profile/sejal.s...,VIS_001
4,"Singh, Harmanjot","Aginas, Gayle",https://public.tableau.com/views/GayleAginas-D...,VIS_002
...,...,...,...,...
159,"Friesen, Adelle","Wagner-Joseph, Tyler",https://public.tableau.com/app/profile/tyler.w...,VIS_040
160,"Khushi, .","Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,VIS_041
161,"Frost, Martina","Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,VIS_041
162,"Singh, Sehajpal","Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,VIS_041
163,"Shang, Sarah","Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,VIS_041

In [93]:
reviewer_count_dict

{'Jia, Skylar': 4,
 'Gomms, Eagan': 4,
 'Lovedeep, .': 4,
 'Na, Tanishka': 4,
 'Rohit, .': 4,
 'Ogbodu, Kennedy': 4,
 'Hounsell, Tori': 4,
 'Friesen, Adelle': 4,
 'Kajoba, Benjamin': 4,
 'Singh, Harmanjot': 4,
 'Frost, Martina': 4,
 'Peng, Aesir': 4,
 'Kaur, Jaipreet': 4,
 'Lavallee, Danielle': 4,
 'Kohli, Brahmmeet Singh': 4,
 'Gurtar Singh, .': 4,
 'Sejal': 4,
 'Wagner-Joseph, Tyler': 4,
 'Singh, Navraj': 4,
 'Tisha, .': 4,
 'Tervonen-Dueck, Addyson': 4,
 'Aginas, Gayle': 4,
 'Knoppers, Jacob': 4,
 'Liboiron, Liam': 4,
 'Pardeep Kaur, .': 4,
 'Khushi, .': 4,
 'Khushpreet Singh, .': 4,
 'Mclean, Aidan': 4,
 'Lnu, Simranpreet Kaur': 4,
 'Apito, Abbygail': 4,
 "Van't Hoff, Edson": 4,
 'Martineau, Kenzie': 4,
 'Felipe, Katrina': 4,
 'Sewers, Pamela': 4,
 'Singh, Sehajpal': 4,
 'Weir, Ethan': 4,
 'Libuna, Chira May': 4,
 'Garcia Moreira Santos, Breno': 4,
 'Janat Madaan, .': 4,
 'Mohamed, Doha': 4,
 'Shang, Sarah': 4}

In [94]:
name_url_df

,Name,URL,Count_Assigned,count
0,Sejal,https://public.tableau.com/app/profile/sejal.s...,40,4
1,"Aginas, Gayle",https://public.tableau.com/views/GayleAginas-D...,40,3
2,"Apito, Abbygail",https://public.tableau.com/shared/7CKX4B72J?:d...,40,6
3,"Felipe, Katrina",https://public.tableau.com/app/profile/katrina...,40,1
4,"Friesen, Adelle",https://public.tableau.com/app/profile/adelle....,40,2
5,"Frost, Martina",https://public.tableau.com/shared/HHJHGCFTN?:d...,40,5
6,"Garcia Moreira Santos, Breno",https://public.tableau.com/views/Assignment3-S...,40,5
7,"Gomms, Eagan",https://public.tableau.com/app/profile/eagan.g...,40,4
8,"Gurtar Singh, .",https://public.tableau.com/views/StoryDATA2210...,40,7
9,"Hounsell, Tori",https://public.tableau.com/views/ProvinceGDPSt...,40,3
10,"Janat Madaan, .",https://public.tableau.com/app/profile/janat.m...,40,2
11,"Jia, Skylar",https://public.tableau.com/views/Book12_176447...,40,6
12,"Kajoba, Benjamin",https://public.tableau.com/app/profile/benjami...,40,10
13,"Kaur, Jaipreet",https://public.tableau.com/app/profile/user125...,40,3
14,"Khushi, .",https://public.tableau.com/app/profile/user125...,40,2
15,"Khushpreet Singh, .",https://public.tableau.com/app/profile/khushpr...,40,4
16,"Knoppers, Jacob",https://public.tableau.com/app/profile/jacob.k...,40,3
17,"Kohli, Brahmmeet Singh",https://public.tableau.com/views/BankCustomerC...,40,4
18,"Lavallee, Danielle",https://public.tableau.com/shared/KJPB8T6GC?:d...,40,6
19,"Liboiron, Liam",https://public.tableau.com/app/profile/liam.li...,40,2
20,"Libuna, Chira May",https://public.tableau.com/shared/KRYWZ2P82?:d...,40,6
21,"Lnu, Simranpreet Kaur",https://public.tableau.com/app/profile/simranp...,40,1
22,"Lovedeep, .",https://public.tableau.com/app/profile/.lovede...,40,2
23,"Martineau, Kenzie",https://public.tableau.com/views/HowWeatherAff...,40,5
24,"Mclean, Aidan",https://public.tableau.com/app/profile/aidan.m...,40,3
25,"Mohamed, Doha",https://public.tableau.com/app/profile/doha.mo...,40,3
26,"Na, Tanishka",https://public.tableau.com/shared/PJPQPTX2P?:d...,40,5
27,"Ogbodu, Kennedy",https://public.tableau.com/app/profile/kennedy...,40,0
28,"Pardeep Kaur, .",https://public.tableau.com/views/StoryAssignme...,40,4
29,"Peng, Aesir",https://public.tableau.com/app/profile/aesir.p...,40,5
30,"Rohit, .",https://public.tableau.com/views/StoryRohit/St...,40,3
31,"Sewers, Pamela",https://public.tableau.com/app/profile/pamela....,40,5
32,"Shang, Sarah",https://public.tableau.com/app/profile/sarah.s...,40,5
33,"Singh, Harmanjot",https://public.tableau.com/views/Storyyyy_1764...,40,2
34,"Singh, Navraj",https://public.tableau.com/views/Story_1764463...,40,5
35,"Singh, Sehajpal",https://public.tableau.com/app/profile/sehajpa...,40,6
36,"Tervonen-Dueck, Addyson",https://public.tableau.com/app/profile/addyson...,40,4
37,"Tisha, .",https://public.tableau.com/app/profile/tisha.t...,40,4
38,"Van't Hoff, Edson",https://public.tableau.com/app/profile/edson.v...,40,3
39,"Wagner-Joseph, Tyler",https://public.tableau.com/app/profile/tyler.w...,40,6
40,"Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,36,5

In [95]:
name_url_df

,Name,URL,Count_Assigned,count
0,Sejal,https://public.tableau.com/app/profile/sejal.s...,40,4
1,"Aginas, Gayle",https://public.tableau.com/views/GayleAginas-D...,40,3
2,"Apito, Abbygail",https://public.tableau.com/shared/7CKX4B72J?:d...,40,6
3,"Felipe, Katrina",https://public.tableau.com/app/profile/katrina...,40,1
4,"Friesen, Adelle",https://public.tableau.com/app/profile/adelle....,40,2
5,"Frost, Martina",https://public.tableau.com/shared/HHJHGCFTN?:d...,40,5
6,"Garcia Moreira Santos, Breno",https://public.tableau.com/views/Assignment3-S...,40,5
7,"Gomms, Eagan",https://public.tableau.com/app/profile/eagan.g...,40,4
8,"Gurtar Singh, .",https://public.tableau.com/views/StoryDATA2210...,40,7
9,"Hounsell, Tori",https://public.tableau.com/views/ProvinceGDPSt...,40,3
10,"Janat Madaan, .",https://public.tableau.com/app/profile/janat.m...,40,2
11,"Jia, Skylar",https://public.tableau.com/views/Book12_176447...,40,6
12,"Kajoba, Benjamin",https://public.tableau.com/app/profile/benjami...,40,10
13,"Kaur, Jaipreet",https://public.tableau.com/app/profile/user125...,40,3
14,"Khushi, .",https://public.tableau.com/app/profile/user125...,40,2
15,"Khushpreet Singh, .",https://public.tableau.com/app/profile/khushpr...,40,4
16,"Knoppers, Jacob",https://public.tableau.com/app/profile/jacob.k...,40,3
17,"Kohli, Brahmmeet Singh",https://public.tableau.com/views/BankCustomerC...,40,4
18,"Lavallee, Danielle",https://public.tableau.com/shared/KJPB8T6GC?:d...,40,6
19,"Liboiron, Liam",https://public.tableau.com/app/profile/liam.li...,40,2
20,"Libuna, Chira May",https://public.tableau.com/shared/KRYWZ2P82?:d...,40,6
21,"Lnu, Simranpreet Kaur",https://public.tableau.com/app/profile/simranp...,40,1
22,"Lovedeep, .",https://public.tableau.com/app/profile/.lovede...,40,2
23,"Martineau, Kenzie",https://public.tableau.com/views/HowWeatherAff...,40,5
24,"Mclean, Aidan",https://public.tableau.com/app/profile/aidan.m...,40,3
25,"Mohamed, Doha",https://public.tableau.com/app/profile/doha.mo...,40,3
26,"Na, Tanishka",https://public.tableau.com/shared/PJPQPTX2P?:d...,40,5
27,"Ogbodu, Kennedy",https://public.tableau.com/app/profile/kennedy...,40,0
28,"Pardeep Kaur, .",https://public.tableau.com/views/StoryAssignme...,40,4
29,"Peng, Aesir",https://public.tableau.com/app/profile/aesir.p...,40,5
30,"Rohit, .",https://public.tableau.com/views/StoryRohit/St...,40,3
31,"Sewers, Pamela",https://public.tableau.com/app/profile/pamela....,40,5
32,"Shang, Sarah",https://public.tableau.com/app/profile/sarah.s...,40,5
33,"Singh, Harmanjot",https://public.tableau.com/views/Storyyyy_1764...,40,2
34,"Singh, Navraj",https://public.tableau.com/views/Story_1764463...,40,5
35,"Singh, Sehajpal",https://public.tableau.com/app/profile/sehajpa...,40,6
36,"Tervonen-Dueck, Addyson",https://public.tableau.com/app/profile/addyson...,40,4
37,"Tisha, .",https://public.tableau.com/app/profile/tisha.t...,40,4
38,"Van't Hoff, Edson",https://public.tableau.com/app/profile/edson.v...,40,3
39,"Wagner-Joseph, Tyler",https://public.tableau.com/app/profile/tyler.w...,40,6
40,"Weir, Ethan",https://public.tableau.com/app/profile/ethan.w...,36,5